/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

/**
 *
 * @author perpustakaan
 */
public class DlgLapor extends javax.swing.JDialog {

    
    public DlgLapor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,10);
        setSize(465,515);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jLabel6 = new javax.swing.JLabel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel38 = new javax.swing.JLabel();
        BtnLaporIT = new widget.Button();
        jLabel37 = new javax.swing.JLabel();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ About Program ]::");
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Lapor IT & Maintenance ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(50, 50, 50));
        jLabel6.setText(".: Segera Lapor ");
        jLabel6.setName("jLabel6"); // NOI18N
        internalFrame1.add(jLabel6);
        jLabel6.setBounds(10, 18, 90, 20);

        panelGlass1.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass1.setOpaqueImage(false);
        panelGlass1.setRound(false);
        panelGlass1.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(50, 50, 50));
        jLabel38.setText("Untuk lapor IT klik Tombol Lapor IT");
        jLabel38.setName("jLabel38"); // NOI18N
        panelGlass1.add(jLabel38);
        jLabel38.setBounds(30, 10, 210, 14);

        BtnLaporIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
        BtnLaporIT.setMnemonic('K');
        BtnLaporIT.setText("Lapor IT");
        BtnLaporIT.setToolTipText("Alt+K");
        BtnLaporIT.setGlassColor(new java.awt.Color(153, 255, 153));
        BtnLaporIT.setIconTextGap(3);
        BtnLaporIT.setName("BtnLaporIT"); // NOI18N
        BtnLaporIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaporITActionPerformed(evt);
            }
        });
        BtnLaporIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnLaporITKeyPressed(evt);
            }
        });
        panelGlass1.add(BtnLaporIT);
        BtnLaporIT.setBounds(20, 50, 190, 60);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(50, 50, 50));
        jLabel37.setText("Klik close untuk Keluar dari Menu Ini......");
        jLabel37.setName("jLabel37"); // NOI18N
        panelGlass1.add(jLabel37);
        jLabel37.setBounds(340, 80, 210, 14);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Close");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass1.add(BtnKeluar);
        BtnKeluar.setBounds(360, 100, 140, 50);

        internalFrame1.add(panelGlass1);
        panelGlass1.setBounds(20, 40, 580, 160);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLaporITKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnLaporITKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            BtnLaporITActionPerformed(null);
        }
    }//GEN-LAST:event_BtnLaporITKeyPressed

    private void BtnLaporITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaporITActionPerformed
        // TODO add your handling code here:
        try {
            // Alamat website laporan Anda (Ganti localhost dengan IP Server jika berbeda PC)
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://itrepots.permatakeluarga.com/lapor_publik.php"));
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
    }//GEN-LAST:event_BtnLaporITActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgLapor dialog = new DlgLapor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnLaporIT;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel6;
    private usu.widget.glass.PanelGlass panelGlass1;
    // End of variables declaration//GEN-END:variables

}
